

spring:
  application:
    name: microservice-discovery-eureka-ha
---

spring:
    profiles: peer1
server.port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: peer1
eureka.client.service-url:
  defaultZone: http://peer2:8762/eureka/
---
spring:
    profiles: peer2
server.port: 8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: peer2
eureka.client.service-url:
  defaultZone: http://peer1:8761/eureka/
