server.port: 8030
info.app.name: @project.artifactId@

spring:
  application:
    name: microservice-consumer-movie-hystorix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address:  true
