server.port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: microservice-discovery-eureka


